project_id = "pczauvcscdpazzyehtxk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.scheduled-tasks]
    verify_jwt = false
  [functions.send-2fa-code]
    verify_jwt = false
  [functions.send-parent-invite]
    verify_jwt = false
  [functions.send-push-notification]
    verify_jwt = false
  [functions.verify-2fa]
    verify_jwt = false
